  
version: '3'

services:
    database:
        image: mariadb:${DB_VERSION}
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - 127.0.0.1:${DB_PORT}:3306
        container_name: ${DB_CONTAINER_NAME}
        restart: unless-stopped
        volumes:
            - "./datadb:/datadb"
    web: 
        image: hymedboussaklatan/web-groupe-16
        container_name: web
        restart: always
        ports: 
            - "80:80/tcp"
            - "443:443/tcp" 
